### ISSUE TITLE
board select with board name instead of selecting one from list

### ISSUE THREAD

**Issue by pointbre** [qcam/3llo#37]
First of all, thanks for your work. 

Would it be possible to introduce a board name argument to board select command instead of selecting board from list?

[AS-IS]
```
3llo  > board select
Board to select:
  board 1
‣ board 2
  board 3

 3llo  > board select
Board to select:  board 2

Board board 2 selected

 3llo  >
```

[TO-BE]
```
[AS-IS]
3llo  > board select "board 2"
3llo  > board select "board 2"
Board to select:  board 2

Board board 2 selected

 3llo  >
```

The reason why I'm requesting this feature is to use 3llo for trello automation(batch mode). I'd think all of commands of 3llo works by piping series of command  like the following:

```
echo 'card show aaaaaaaaaaaaaaaaa
> exit' | 3llo


    3llo - CLI for Trello

    Usage:
    board list                   - Show list of board
    board select                 - Select board
    card list                    - Show list of cards grouped by list
    card list mine               - Show list of my cards
    card add                     - Create a card
    card show <card_id>          - Show card information
    card move <card_id>          - Move card to a list
    card self-assign <card_id>   - Self-assign a card
    card assign <card_id>        - Assign a user to a card
    card comments <card_id>      - Load recent comments of a card
    card comment <card_id>       - Add a comment to a card
    card archive <card_id>       - Archive a card
    list list                    - Show all lists
    list cards <list_id>         - Show all cards in list
    list archive-cards <list_id> - Archive all cards in list
    help                         - Show help menu
    exit                         - Exit program


 3llo  > card show aaaaaaaaaaaaaaaaa

ID: aaaaaaaaaaaaaaaaa
Name: Title
Description: 
...

 3llo  > exit
Bye bye
```

However, this trick doesn't work for board select and I have failed to find another trick. If I can use board select command with board name argument, without any extra enhancement, I will be able to use 3llo for automation which is great.

Lucas

**Comment by CheRuisiBesares** [comment]
I would also love a way to specify the board for batch commands. Idk if people would be open to adding some flags to the `3llo` command that would set some defaults. Maybe something like

`3llo -b "<board id>"`

or we could set the default with an environment var as well or instead of?

`DEFAULT_BOARD_ID="<board id>" 3llo`

Anyway thanks for making this tool. I find it helpful already. I would love to make it more script-able but not sure if that is the intended direction.

**Comment by qcam** [comment]
Closed via https://github.com/qcam/3llo/commit/93e1ccdb80985d75ff48bc5fa7d381e989bde2e6.

With that commit introduced, one now can specify `3llo --init="board select <board_id>"` to select a board.
